controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_arm_controller:
  ros__parameters:
    joints:
      - pan_joint
      - shoulder_joint
      - elbow_joint
      - wrist0_joint
      - wrist1_joint
      - wrist2_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity